### ISSUE TITLE
God damn it

### ISSUE THREAD

**Issue by MccTube** [kota69th/CreativeExpansionPack#3]
The site keeps crashing so imma keep this quick, you said it didn’t break EULA bcz it didn’t offer competitive advantage over other players and that’s true. BUT, (note; by using the game you agree to the Eula and if you break the EULA you are basically required to quit the game, or get banned lol) AND I QUOTE; To provide users with a positive, fair, and competitive experience on the Services, we may use certain software, tools, and technologies (“Fraud and Cheat Detection”) to detect and prevent programs, methods, or other processes that (i) are used for hacking, account stealing, or other unauthorized or fraudulent activity on the Services (“Fraud”) or (ii) give you or other users a competitive advantage within the Services (“Cheats”), including bots, hacks, add-ons, malware, scripts, **and mods not expressly authorized by us.** You will not:
a. **Use or encourage the use of Cheats;**
b. Engage in or encourage others to engage in Fraud;
c. **Develop, market, offer, sell, distribute, support or otherwise make available any Cheats;** or
d. Attempt to tamper with, modify, disable, disrupt, or circumvent any software, tools or technologies used to detect and prevent Fraud or Cheats.

Uh oh. This is a mod not expressly authorized by “us”.
This is probably all exaggerated in the EULA but please help me kota, I really don’t wanna go to court. Thanks.

**Comment by kota69th** [comment]
The Fall Guys EULA is written so that Mediatonic and Epic Games have control over their game and it's whole surroudings. 

It's up to them to tell if Creative Expansion Pack is actually a threat to the game and should be considered as unauthorized.

However, Creative Expansion Pack is also open-source, meaning that anyone (including anyone working on Fall Guys) can take a look at the code that makes up this project.

My point is that Creative Expansion Pack by itself doesn't oppose any threat to the competitive experience of a user, and can't be considered as a proper "cheating" software if we look at it from the EULA's point of view.

I'm grateful about the fact that in the meantime, Mediatonic and Epic Games seems fine with the existence of Creative Expansion Pack, and I thank them for that.

**Comment by MccTube** [comment]
That’s true actually. I don’t think they care at all! I think they enjoy seeing what the community can do, as long as it’s not malicious. Thank you for making this mod 👍
